# ansible/inventories/prod/hosts.yml
---
all:
  children:
    appservers:
      hosts:
        cmdb-prod-app01:
          ansible_host: 10.10.1.10
        cmdb-prod-app02:
          ansible_host: 10.10.1.11
    dbservers:
      hosts:
        cmdb-prod-db01:
          ansible_host: 10.10.1.20
    jenkins:
      hosts:
        cmdb-prod-ci01:
          ansible_host: 10.10.1.30
