# ansible/inventories/staging/hosts.yml
---
all:
  children:
    appservers:
      hosts:
        cmdb-stg-app01:
          ansible_host: 10.0.1.10
    dbservers:
      hosts:
        cmdb-stg-db01:
          ansible_host: 10.0.1.11
    jenkins:
      hosts:
        cmdb-stg-ci01:
          ansible_host: 10.0.1.12
